name: Chocorot-ServerEnhancer
main: net.chocorot.chocorotServerEnhancer.Main
version: 1.0.0
api-version: 1.8.8
author: Chocorot
description: A plugin that made for Chocorot Network to enchance the server
commands:
   cse:
      description: Main Command
      permission: chocorot.admin
   
   fly:
      description: Toggle fly
      permission: chocorot.fly
   ping:
      description: Display player current ping
      permission: 
   pkcheat:
      description: DONT CHEAT
      permission: op